= Exercise: Control(ler) that Automation!

== Acknowledgements

Most of this exercise was taken from our Developing Advanced Automation (DO374) course; credit to the Red Hat Training team that developed the course for those elements! *Ask a Red Hat team member about how you can continue your learning with a Red Hat Learning Subscription or through general Red Hat Training courses!*

== Goals

* Create source control and machine credentials.
* Create a project.
* Create an inventory that uses an inventory file from the project.
* Create a new job template.
* Launch a job template and review the output generated by the job.

== pass:a,n[{gls_res_prereqs}]
As the `student` user on the `workstation` machine, use the `lab` command to prepare your system for this exercise.

This command creates the Git repository used by this exercise.

[subs="+quotes"]
----
[student@workstation ~]$ *lab start controller-playbooks*
----

[role='Checklist']
== pass:a,n[{gls_res_instructions}]

This exercise provides you with an Ansible project in a Git repository that contains a working playbook to deploy a simple web server.

[]
1. Automation controller must have a _source control credential_ to access content from a Git repository.
From the automation controller web UI, create a source control credential named `Git Project Credential`.
Configure this credential to use authentication information for the `git.lab.example.com` server.
.. Navigate to `\https://controller.lab.example.com` and log in as `admin` using `redhat` as the password.
.. Navigate to menu:Resources[Credentials] and click btn:[Add].
Create the credential with the following settings and then click btn:[Save].
+
--
[cols="1,2",options="header"]
|===
|Field|Value
|btn:[Name]|`Git Project Credential`
|btn:[Organization]|`Default`
|btn:[Credential Type]|`Source Control`
|btn:[Username]|`student`
|btn:[SCM Private Key]|Content of the `/home/student/.ssh/gitlab_rsa` file.
|===

[NOTE]
====
If you choose to browse for the file, then right-click anywhere in the directory navigation and select btn:[Show Hidden Files].
With this option enabled you can see the `.ssh` directory in the `/home/student` directory.
====
--
2. To run the playbook against each managed host, automation controller must have a _machine credential_ that contains authentication information.
Create a machine credential named `Devops Machine Credential` that contains authentication information for the managed hosts in the classroom environment.
.. Navigate to menu:Resources[Credentials] and click btn:[Add].
Create the credential with the following settings and then click btn:[Save].
+
--
[cols="3,5",options="header"]
|===
|Field|Value
|btn:[Name]|`Devops Machine Credential`
|btn:[Organization]|`Default`
|btn:[Credential Type]|`Machine`
|btn:[Username]|`devops`
|btn:[SSH Private Key]|Content of the `/home/student/.ssh/lab_rsa` file.
|btn:[Privilege Escalation Method]|`sudo`
|btn:[Privilege Escalation Username]|`root`
|===

[NOTE]
====
If you choose to browse for the file, then right-click anywhere in the directory navigation and select btn:[Show Hidden Files].
This lets you see the `.ssh` directory in the `/home/student` directory.
====
--
3. Create a project named `Controller Playbooks Project`.
This project points to a Git repository that contains a playbook and an inventory file.
Configure the project to specify a default automation execution environment.
.. Navigate to menu:Resources[Projects] and then click btn:[Add].
Create the project with the following settings and then click btn:[Save].
+
--
[cols="3,5",options="header"]
|===
|Field|Value
|btn:[Name]|`Controller Playbooks Project`
|btn:[Organization]|`Default`
|btn:[Execution Environment]|`Automation Hub Default execution environment`
|btn:[Source Control Type]|`Git`
|btn:[Source Control URL]|`git@git.lab.example.com:student/controller-playbooks.git`
|btn:[Source Control Credential]|`Git Project Credential`
|btn:[Options]|`Allow Branch Override`
|===

After you click btn:[Save], automation controller immediately attempts to synchronize the project.
The project synchronization should succeed.

[IMPORTANT]
====
If synchronization fails, ensure that the project specifies the correct source control URL and credentials and then attempt the project synchronization again.
====
--
4. Create an inventory for this exercise named `Controller Playbooks Inventory (Dev)` using the `inventory` file in the project repository.
+
--
Managing your inventory file in a Git repository enables you to benefit from storing your changes in a version control system.
You can also update it by editing the file rather than manually updating inventory information in the automation controller web UI.
--
.. Navigate to menu:Resources[Inventories] and then click menu:Add[Add inventory].
.. Create a new inventory with the following settings and then click btn:[Save].
+
--
[cols="3,5",options="header"]
|===
|Field|Value
|btn:[Name]|`Controller Playbooks Inventory (Dev)`
|btn:[Organization]|`Default`
|===
--
.. From the btn:[Sources] tab, click btn:[Add].
Create a new inventory source with the following settings and then click btn:[Save].
+
--
[NOTE]
====
After selecting the project, you might see the following error message: `That value was not found. Please enter or select a valid value.`
The error message disappears when you select the inventory file.
====

[cols="3,5",options="header"]
|===
|Field|Value
|btn:[Name]|`Controller Playbooks Source (Dev)`
|btn:[Source]|`Sourced from a Project`
|btn:[Project]|`Controller Playbooks Project`
|btn:[Inventory file]|`inventory`
|btn:[Options]|`Update on project update`
|===
--
.. Click btn:[Sources] in the breadcrumb navigator and then click the btn:[Start sync process] icon for the btn:[Controller Playbooks Source (Dev)] source.
The status updates to indicate that the synchronization succeeded.
.. Click the btn:[Hosts] tab.
The inventory source imported the `serverf.lab.example.com` host.
.. Click the btn:[Groups] tab.
The inventory source imported the `web` group.
.. Click btn:[web] and then click the btn:[Hosts] tab.
The `web` group contains the `serverf.lab.example.com` host.
5. Create a job template named `Basic Web`.
Configure the job template to run the `basic-web-fqcn.yml` playbook using the default automation execution environment for the project.
The playbook ensures that a web server and its content are deployed on hosts in the `web` inventory host group.
.. Navigate to menu:Resources[Templates] and then click menu:Add[Add job template].
Create the new job template with the following settings, and then click btn:[Save].
+
--
[cols="3,5",options="header"]
|===
|Field|Value
|btn:[Name]|`Basic Web`
|btn:[Inventory]|`Controller Playbooks Inventory (Dev)`
|btn:[Project]|`Controller Playbooks Project`
|btn:[Playbook]|`basic-web-fqcn.yml`
|btn:[Credentials]|`Devops Machine Credential`
|===
--
.. Click btn:[Launch] to run the job template.
The resulting job successfully runs the playbook.
.. Navigate to menu:Views[Jobs] and look for a numbered job with `Basic Web` in the name.
By default, automation controller lists the most recent jobs at the top.
The `Basic Web` job displays a status of btn:[Successful].
.. _(Optional)_ Click the name of the `Basic Web` job to review the job output.
This is the same output that you initially saw when you launched the job.
.. Verify that the job successfully deployed a web server on `serverf.lab.example.com`.
From a terminal window, run the `curl` command to access web content at `\http://serverf.lab.example.com`.
+
--
[subs="+quotes"]
----
[student@workstation ~]$ *curl http://serverf.lab.example.com*
Hello world from serverf.lab.example.com.
----
--